sonar.projectKey=rappit_ps_test_automation_base
sonar.projectName=ps-test-automation-base
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/dist/**,**/node_modules/**,**/logs/**,**/test-results/**,**/Automation/**,**/docs/**
sonar.test.inclusions=tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Keep scanner stable for TypeScript monorepo style structures
sonar.typescript.tsconfigPath=tsconfig.json
